[[pages]]
name = "Eingabemasken"
icon = "ğŸ“©"
is_section = true

[[pages]]
path = "pages/1_Einbuchung.py"
name = "Einbuchung Produkt"
icon = "â¡ï¸"

[[pages]]
path = "pages/2_Aktualisierung.py"
name = "Aktualisierung Produktwert"
icon = "ğŸ”„"

[[pages]]
path = "pages/3_Ausbuchung.py"
name = "Ausbuchung Produkt"
icon = "â¬…ï¸"

[[pages]]
name = "Overview"
icon = "ğŸ“Š"
is_section = true

[[pages]]
path = "pages/4_search_filter_edit.py"
name = "Search / Filter / Edit"
icon = "ğŸ”"

[[pages]]
path = "pages/5_Auswertungen.py"
name = "Auswertungen"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/6_Lagerbestand.py"
name = "Lagerbestand"
icon = "ğŸ”‹"